/*
 * Webhook Type Definition
 *
 * Webhook event definition of the LINE Messaging API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct AttachedModuleContent {
    /// Type
    #[serde(rename = "type")]
    pub r#type: String,
    /// User ID of the bot on the attached LINE Official Account
    #[serde(rename = "botId")]
    pub bot_id: String,
    /// An array of strings indicating the scope permitted by the admin of the LINE Official Account.
    #[serde(rename = "scopes")]
    pub scopes: Vec<String>,
}

impl AttachedModuleContent {
    pub fn new(r#type: String, bot_id: String, scopes: Vec<String>) -> AttachedModuleContent {
        AttachedModuleContent {
            r#type,
            bot_id,
            scopes,
        }
    }
}

