/*
 * Webhook Type Definition
 *
 * Webhook event definition of the LINE Messaging API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// BeaconEvent : Event object for when a user enters the range of a LINE Beacon. You can reply to beacon events.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct BeaconEvent {
    /// Type of the event
    #[serde(rename = "type")]
    pub r#type: String,
    #[serde(rename = "source", skip_serializing_if = "Option::is_none")]
    pub source: Option<Box<models::Source>>,
    /// Time of the event in milliseconds.
    #[serde(rename = "timestamp")]
    pub timestamp: i64,
    #[serde(rename = "mode")]
    pub mode: models::EventMode,
    /// Webhook Event ID. An ID that uniquely identifies a webhook event. This is a string in ULID format.
    #[serde(rename = "webhookEventId")]
    pub webhook_event_id: String,
    #[serde(rename = "deliveryContext")]
    pub delivery_context: Box<models::DeliveryContext>,
    /// Reply token used to send reply message to this event
    #[serde(rename = "replyToken")]
    pub reply_token: String,
    #[serde(rename = "beacon")]
    pub beacon: Box<models::BeaconContent>,
}

impl BeaconEvent {
    /// Event object for when a user enters the range of a LINE Beacon. You can reply to beacon events.
    pub fn new(r#type: String, timestamp: i64, mode: models::EventMode, webhook_event_id: String, delivery_context: models::DeliveryContext, reply_token: String, beacon: models::BeaconContent) -> BeaconEvent {
        BeaconEvent {
            r#type,
            source: None,
            timestamp,
            mode,
            webhook_event_id,
            delivery_context: Box::new(delivery_context),
            reply_token,
            beacon: Box::new(beacon),
        }
    }
}

