/*
 * Webhook Type Definition
 *
 * Webhook event definition of the LINE Messaging API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// CallbackRequest : The request body contains a JSON object with the user ID of a bot that should receive webhook events and an array of webhook event objects. 
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct CallbackRequest {
    /// User ID of a bot that should receive webhook events. The user ID value is a string that matches the regular expression, `U[0-9a-f]{32}`. 
    #[serde(rename = "destination")]
    pub destination: String,
    /// Array of webhook event objects. The LINE Platform may send an empty array that doesn't include a webhook event object to confirm communication. 
    #[serde(rename = "events")]
    pub events: Vec<models::Event>,
}

impl CallbackRequest {
    /// The request body contains a JSON object with the user ID of a bot that should receive webhook events and an array of webhook event objects. 
    pub fn new(destination: String, events: Vec<models::Event>) -> CallbackRequest {
        CallbackRequest {
            destination,
            events,
        }
    }
}

