/*
 * Webhook Type Definition
 *
 * Webhook event definition of the LINE Messaging API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ChatControl {
    #[serde(rename = "expireAt")]
    pub expire_at: i64,
}

impl ChatControl {
    pub fn new(expire_at: i64) -> ChatControl {
        ChatControl {
            expire_at,
        }
    }
}

