/*
 * Webhook Type Definition
 *
 * Webhook event definition of the LINE Messaging API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// DeliveryContext : webhook's delivery context information
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct DeliveryContext {
    /// Whether the webhook event is a redelivered one or not.
    #[serde(rename = "isRedelivery")]
    pub is_redelivery: bool,
}

impl DeliveryContext {
    /// webhook's delivery context information
    pub fn new(is_redelivery: bool) -> DeliveryContext {
        DeliveryContext {
            is_redelivery,
        }
    }
}

