/*
 * Webhook Type Definition
 *
 * Webhook event definition of the LINE Messaging API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct Emoji {
    /// Index position for a character in text, with the first character being at position 0.
    #[serde(rename = "index")]
    pub index: i32,
    /// The length of the LINE emoji string. For LINE emoji (hello), 7 is the length.
    #[serde(rename = "length")]
    pub length: i32,
    /// Product ID for a LINE emoji set.
    #[serde(rename = "productId")]
    pub product_id: String,
    /// ID for a LINE emoji inside a set.
    #[serde(rename = "emojiId")]
    pub emoji_id: String,
}

impl Emoji {
    pub fn new(index: i32, length: i32, product_id: String, emoji_id: String) -> Emoji {
        Emoji {
            index,
            length,
            product_id,
            emoji_id,
        }
    }
}

