/*
 * Webhook Type Definition
 *
 * Webhook event definition of the LINE Messaging API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// EventMode : Channel state.
/// Channel state.
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum EventMode {
    #[serde(rename = "active")]
    Active,
    #[serde(rename = "standby")]
    Standby,

}

impl std::fmt::Display for EventMode {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Self::Active => write!(f, "active"),
            Self::Standby => write!(f, "standby"),
        }
    }
}

impl Default for EventMode {
    fn default() -> EventMode {
        Self::Active
    }
}

