/*
 * Webhook Type Definition
 *
 * Webhook event definition of the LINE Messaging API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ImageMessageContent {
    /// Type
    #[serde(rename = "type")]
    pub r#type: String,
    /// Message ID
    #[serde(rename = "id")]
    pub id: String,
    #[serde(rename = "contentProvider")]
    pub content_provider: Box<models::ContentProvider>,
    #[serde(rename = "imageSet", skip_serializing_if = "Option::is_none")]
    pub image_set: Option<Box<models::ImageSet>>,
    /// Quote token to quote this message. 
    #[serde(rename = "quoteToken")]
    pub quote_token: String,
}

impl ImageMessageContent {
    pub fn new(r#type: String, id: String, content_provider: models::ContentProvider, quote_token: String) -> ImageMessageContent {
        ImageMessageContent {
            r#type,
            id,
            content_provider: Box::new(content_provider),
            image_set: None,
            quote_token,
        }
    }
}

