/*
 * Webhook Type Definition
 *
 * Webhook event definition of the LINE Messaging API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// LinkContent : Content of the account link event.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct LinkContent {
    /// One of the following values to indicate whether linking the account was successful or not
    #[serde(rename = "result")]
    pub result: Result,
    /// Specified nonce (number used once) when verifying the user ID.
    #[serde(rename = "nonce")]
    pub nonce: String,
}

impl LinkContent {
    /// Content of the account link event.
    pub fn new(result: Result, nonce: String) -> LinkContent {
        LinkContent {
            result,
            nonce,
        }
    }
}
/// One of the following values to indicate whether linking the account was successful or not
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Result {
    #[serde(rename = "ok")]
    Ok,
    #[serde(rename = "failed")]
    Failed,
}

impl Default for Result {
    fn default() -> Result {
        Self::Ok
    }
}

