/*
 * Webhook Type Definition
 *
 * Webhook event definition of the LINE Messaging API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// MembershipContent : Content of the membership event.
#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
#[serde(tag = "type")]
pub enum MembershipContent {
    #[serde(rename="joined")]
    JoinedMembershipContent {
    },
    #[serde(rename="left")]
    LeftMembershipContent {
    },
    #[serde(rename="renewed")]
    RenewedMembershipContent {
    },
}

impl Default for MembershipContent {
    fn default() -> Self {
        Self::JoinedMembershipContent {
        }
        
    }
}


