/*
 * Webhook Type Definition
 *
 * Webhook event definition of the LINE Messaging API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// PnpDelivery : A delivery object containing a hashed phone number string or a string specified by `X-Line-Delivery-Tag` header
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct PnpDelivery {
    /// A hashed phone number string or a string specified by `X-Line-Delivery-Tag` header
    #[serde(rename = "data")]
    pub data: String,
}

impl PnpDelivery {
    /// A delivery object containing a hashed phone number string or a string specified by `X-Line-Delivery-Tag` header
    pub fn new(data: String) -> PnpDelivery {
        PnpDelivery {
            data,
        }
    }
}

