/*
 * Webhook Type Definition
 *
 * Webhook event definition of the LINE Messaging API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct UnlinkThingsContent {
    /// Type
    #[serde(rename = "type")]
    pub r#type: String,
    /// Device ID of the device that has been linked with LINE.
    #[serde(rename = "deviceId")]
    pub device_id: String,
}

impl UnlinkThingsContent {
    pub fn new(r#type: String, device_id: String) -> UnlinkThingsContent {
        UnlinkThingsContent {
            r#type,
            device_id,
        }
    }
}

