/*
 * Webhook Type Definition
 *
 * Webhook event definition of the LINE Messaging API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct UserSource {
    /// source type
    #[serde(rename = "type")]
    pub r#type: String,
    /// ID of the source user
    #[serde(rename = "userId", skip_serializing_if = "Option::is_none")]
    pub user_id: Option<String>,
}

impl UserSource {
    pub fn new(r#type: String) -> UserSource {
        UserSource {
            r#type,
            user_id: None,
        }
    }
}

