/*
 * Webhook Type Definition
 *
 * Webhook event definition of the LINE Messaging API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct VideoMessageContent {
    /// Type
    #[serde(rename = "type")]
    pub r#type: String,
    /// Message ID
    #[serde(rename = "id")]
    pub id: String,
    /// Length of video file (milliseconds)
    #[serde(rename = "duration", skip_serializing_if = "Option::is_none")]
    pub duration: Option<i64>,
    #[serde(rename = "contentProvider")]
    pub content_provider: Box<models::ContentProvider>,
    /// Quote token to quote this message. 
    #[serde(rename = "quoteToken")]
    pub quote_token: String,
}

impl VideoMessageContent {
    pub fn new(r#type: String, id: String, content_provider: models::ContentProvider, quote_token: String) -> VideoMessageContent {
        VideoMessageContent {
            r#type,
            id,
            duration: None,
            content_provider: Box::new(content_provider),
            quote_token,
        }
    }
}

